import mongoose, { Schema, InferSchemaType } from "mongoose";

export const TECHNOLOGIES = [
  "javascript",
  "typescript",
  "python",
  "java",
  "csharp",
  "cpp",
  "c",
  "go",
  "rust",
  "php",
  "ruby",
  "swift",
  "kotlin",
  "dart",
  "scala",
  "elixir",
  "r",

  "react",
  "vue",
  "angular",
  "svelte",
  "nextjs",
  "nuxt",
  "remix",
  "sveltekit",
  "solid",
  "astro",
  "jquery",

  "nodejs",
  "express",
  "nestjs",
  "fastify",
  "django",
  "flask",
  "fastapi",
  "spring",
  "laravel",
  "symfony",
  "rails",
  "aspnet",
  "dotnet",
  "gin",
  "fiber",

  "react-native",
  "flutter",
  "ionic",

  "sql",
  "postgresql",
  "mysql",
  "mongodb",
  "redis",
  "prisma",
  "typeorm",
  "sequelize",
  "graphql",

  "docker",
  "kubernetes",
  "terraform",
  "ansible",
  "nginx",

  "html",
  "css",
  "scss",
  "sass",
  "tailwind",
  "bootstrap",

  "jest",
  "vitest",
  "cypress",
  "playwright",
  "mocha",

  "vite",
  "webpack",
  "esbuild",
  "rollup",

  "firebase",
  "supabase",
  "strapi",

  "electron",
  "tauri",

  "bash",
  "powershell",
  "regex",
] as const;

export const USE_CASES = [
  "crud",
  "database",
  "api",
  "graphql",
  "rest-api",
  "search",
  "pagination",
  "filtering",
  "sorting",
  "auth",
  "authentication",
  "authorization",
  "jwt",
  "oauth",
  "session",
  "encryption",
  "hashing",
  "validation",
  "form-handling",
  "schema-validation",
  "upload",
  "file-handling",
  "image-processing",
  "download",
  "email",
  "notifications",
  "webhooks",
  "websocket",
  "realtime",
  "date",
  "datetime",
  "timezone",
  "error-handling",
  "logging",
  "monitoring",
  "debugging",
  "middleware",
  "routing",
  "cors",
  "rate-limiting",
  "caching",
  "hooks",
  "components",
  "state-management",
  "styling",
  "animation",
  "responsive-design",
  "testing",
  "unit-testing",
  "integration-testing",
  "e2e-testing",
  "deployment",
  "docker",
  "ci-cd",
  "optimization",
  "performance",
  "lazy-loading",
  "utils",
  "helpers",
  "config",
  "algorithm",
  "data-structure",
] as const;

const snippetSchema = new Schema(
  {
    title: {
      type: String,
      required: [true, "A title is required"],
      trim: true,
      maxlength: [100, "Title cannot exceed 100 characters"],
    },
    description: {
      type: String,
      required: [true, "A description is required"],
      trim: true,
      maxlength: [500, "Description cannot exceed 500 characters"],
    },
    code: {
      type: String,
      required: [true, "A code is required"],
      maxlength: [50000, "Code cannot exceed 50000 characters"],
    },
    technology: {
      type: String,
      required: [true, "A technology is required"],
      enum: {
        values: TECHNOLOGIES,
        message: "This technology is not valid",
      },
    },
    useCase: {
      type: String,
      required: [true, "A use case is required"],
      enum: {
        values: USE_CASES,
        message: "This use case is not valid",
      },
    },
    likesCount: {
      type: Number,
      default: 0,
      min: 0,
    },
    dislikesCount: {
      type: Number,
      default: 0,
      min: 0,
    },
    commentsCount: {
      type: Number,
      default: 0,
      min: 0,
    },
    isPublic: {
      type: Boolean,
      default: true,
    },
    author: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
  },
  {
    timestamps: true,
  }
);

snippetSchema.index({ title: "text", description: "text" });
snippetSchema.index({ technology: 1, useCase: 1 });
snippetSchema.index({ createdAt: -1 });
snippetSchema.index({ author: 1 });
snippetSchema.index({ isPublic: 1 });

export type Snippet = InferSchemaType<typeof snippetSchema>;
export const Snippet = mongoose.model("Snippet", snippetSchema);
export type SnippetDocument = InstanceType<typeof Snippet>;
