// ============================================
// Shared types for Snippex
// Single source of truth for frontend & backend
// ============================================

export const TECHNOLOGIES = [
  "javascript",
  "typescript",
  "python",
  "java",
  "csharp",
  "cpp",
  "c",
  "go",
  "rust",
  "php",
  "ruby",
  "swift",
  "kotlin",
  "dart",
  "scala",
  "elixir",
  "r",
  "react",
  "vue",
  "angular",
  "svelte",
  "nextjs",
  "nuxt",
  "remix",
  "sveltekit",
  "solid",
  "astro",
  "jquery",
  "nodejs",
  "express",
  "nestjs",
  "fastify",
  "django",
  "flask",
  "fastapi",
  "spring",
  "laravel",
  "symfony",
  "rails",
  "aspnet",
  "dotnet",
  "gin",
  "fiber",
  "react-native",
  "flutter",
  "ionic",
  "sql",
  "postgresql",
  "mysql",
  "mongodb",
  "redis",
  "prisma",
  "typeorm",
  "sequelize",
  "graphql",
  "docker",
  "kubernetes",
  "terraform",
  "ansible",
  "nginx",
  "html",
  "css",
  "scss",
  "sass",
  "tailwind",
  "bootstrap",
  "jest",
  "vitest",
  "cypress",
  "playwright",
  "mocha",
  "vite",
  "webpack",
  "esbuild",
  "rollup",
  "firebase",
  "supabase",
  "strapi",
  "electron",
  "tauri",
  "bash",
  "powershell",
  "regex",
] as const;

export const USE_CASES = [
  "crud",
  "database",
  "api",
  "graphql",
  "rest-api",
  "search",
  "pagination",
  "filtering",
  "sorting",
  "auth",
  "authentication",
  "authorization",
  "jwt",
  "oauth",
  "session",
  "encryption",
  "hashing",
  "validation",
  "form-handling",
  "schema-validation",
  "upload",
  "file-handling",
  "image-processing",
  "download",
  "email",
  "notifications",
  "webhooks",
  "websocket",
  "realtime",
  "date",
  "datetime",
  "timezone",
  "error-handling",
  "logging",
  "monitoring",
  "debugging",
  "middleware",
  "routing",
  "cors",
  "rate-limiting",
  "caching",
  "hooks",
  "components",
  "state-management",
  "styling",
  "animation",
  "responsive-design",
  "testing",
  "unit-testing",
  "integration-testing",
  "e2e-testing",
  "deployment",
  "docker",
  "ci-cd",
  "optimization",
  "performance",
  "lazy-loading",
  "utils",
  "helpers",
  "config",
  "algorithm",
  "data-structure",
] as const;

export type Technology = (typeof TECHNOLOGIES)[number];
export type UseCase = (typeof USE_CASES)[number];
export type SortBy = "newest" | "oldest" | "popular";

export interface Author {
  _id: string;
  username: string;
  profile?: {
    avatarUrl?: string;
  };
}

export interface Snippet {
  _id: string;
  title: string;
  description: string;
  code: string;
  technology: Technology;
  useCase: UseCase;
  likesCount: number;
  dislikesCount: number;
  commentsCount: number;
  isPublic: boolean;
  author: Author;
  createdAt: string;
  updatedAt: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    page: number;
    totalPages: number;
    totalItems: number;
    itemsInPage: number;
    hasNext: boolean;
    hasPrev: boolean;
  };
}

export const TECHNOLOGY_LABELS: Record<Technology, string> = {
  javascript: "JavaScript",
  typescript: "TypeScript",
  python: "Python",
  java: "Java",
  csharp: "C#",
  cpp: "C++",
  c: "C",
  go: "Go",
  rust: "Rust",
  php: "PHP",
  ruby: "Ruby",
  swift: "Swift",
  kotlin: "Kotlin",
  dart: "Dart",
  scala: "Scala",
  elixir: "Elixir",
  r: "R",
  react: "React",
  vue: "Vue",
  angular: "Angular",
  svelte: "Svelte",
  nextjs: "Next.js",
  nuxt: "Nuxt",
  remix: "Remix",
  sveltekit: "SvelteKit",
  solid: "Solid",
  astro: "Astro",
  jquery: "jQuery",
  nodejs: "Node.js",
  express: "Express",
  nestjs: "NestJS",
  fastify: "Fastify",
  django: "Django",
  flask: "Flask",
  fastapi: "FastAPI",
  spring: "Spring",
  laravel: "Laravel",
  symfony: "Symfony",
  rails: "Rails",
  aspnet: "ASP.NET",
  dotnet: ".NET",
  gin: "Gin",
  fiber: "Fiber",
  "react-native": "React Native",
  flutter: "Flutter",
  ionic: "Ionic",
  sql: "SQL",
  postgresql: "PostgreSQL",
  mysql: "MySQL",
  mongodb: "MongoDB",
  redis: "Redis",
  prisma: "Prisma",
  typeorm: "TypeORM",
  sequelize: "Sequelize",
  graphql: "GraphQL",
  docker: "Docker",
  kubernetes: "Kubernetes",
  terraform: "Terraform",
  ansible: "Ansible",
  nginx: "Nginx",
  html: "HTML",
  css: "CSS",
  scss: "SCSS",
  sass: "Sass",
  tailwind: "Tailwind",
  bootstrap: "Bootstrap",
  jest: "Jest",
  vitest: "Vitest",
  cypress: "Cypress",
  playwright: "Playwright",
  mocha: "Mocha",
  vite: "Vite",
  webpack: "Webpack",
  esbuild: "esbuild",
  rollup: "Rollup",
  firebase: "Firebase",
  supabase: "Supabase",
  strapi: "Strapi",
  electron: "Electron",
  tauri: "Tauri",
  bash: "Bash",
  powershell: "PowerShell",
  regex: "Regex",
};

export const USE_CASE_LABELS: Record<UseCase, string> = {
  crud: "CRUD",
  database: "Database",
  api: "API",
  graphql: "GraphQL",
  "rest-api": "REST API",
  search: "Search",
  pagination: "Pagination",
  filtering: "Filtering",
  sorting: "Sorting",
  auth: "Auth",
  authentication: "Authentication",
  authorization: "Authorization",
  jwt: "JWT",
  oauth: "OAuth",
  session: "Session",
  encryption: "Encryption",
  hashing: "Hashing",
  validation: "Validation",
  "form-handling": "Form Handling",
  "schema-validation": "Schema Validation",
  upload: "Upload",
  "file-handling": "File Handling",
  "image-processing": "Image Processing",
  download: "Download",
  email: "Email",
  notifications: "Notifications",
  webhooks: "Webhooks",
  websocket: "WebSocket",
  realtime: "Realtime",
  date: "Date",
  datetime: "DateTime",
  timezone: "Timezone",
  "error-handling": "Error Handling",
  logging: "Logging",
  monitoring: "Monitoring",
  debugging: "Debugging",
  middleware: "Middleware",
  routing: "Routing",
  cors: "CORS",
  "rate-limiting": "Rate Limiting",
  caching: "Caching",
  hooks: "Hooks",
  components: "Components",
  "state-management": "State Management",
  styling: "Styling",
  animation: "Animation",
  "responsive-design": "Responsive Design",
  testing: "Testing",
  "unit-testing": "Unit Testing",
  "integration-testing": "Integration Testing",
  "e2e-testing": "E2E Testing",
  deployment: "Deployment",
  docker: "Docker",
  "ci-cd": "CI/CD",
  optimization: "Optimization",
  performance: "Performance",
  "lazy-loading": "Lazy Loading",
  utils: "Utils",
  helpers: "Helpers",
  config: "Config",
  algorithm: "Algorithm",
  "data-structure": "Data Structure",
};
